languageCode = "en-us"
title = "Cupper"
baseURL = "https://flittle8.github.io/cupper/"
canonifyURLs = true
theme = "cupper"
publishDir = "docs"

[params]
  description = "Making books accessible to all."
  codePenUser = "flittle8"
